### ISSUE TITLE
需要一个API文档

### ISSUE THREAD

**Issue by IM2eR0** [OrgEleCho/EleCho.GoCqHttpSdk#10]
SDK很好，但是我需要一个API文档
我到现在都不知道MessageReceive的时候返回的context数据结构

**Comment by SlimeNull** [comment]
你可能需要, xxxSession.UseXXXX, 它的参数接受一个中间件, 而中间件的参数是与上报对应的 Context. 这个在 readme 中是有提到的, 不过, 感谢你的建议, 我会补充它的文档的

**Comment by SlimeNull** [comment]
另外, 对着一个类型, 右键, 可以跳转到定义, 或者按 F12 也可以. 在 C# 中是这样查阅文档的.

**Comment by IM2eR0** [comment]
> 

了解！非常感谢
