### ISSUE TITLE
UseMessageMatchPlugin在同Session下是否只支持一个Plugin使用

### ISSUE THREAD

**Issue by wearshoes** [OrgEleCho/EleCho.GoCqHttpSdk#13]
session.UseMessageMatchPlugin(new Echo_Plugin(session));
session.UseMessageMatchPlugin(new PikPak_Plugin(session));

我这样调用后，只有Echo_Plugin有回应，代码如下：
Echo_Plugin：
![image](https://user-images.githubusercontent.com/30278479/220835461-c28e6c1e-daad-4116-b0d1-0df07ce97834.png)
PikPak_Plugin：
![image](https://user-images.githubusercontent.com/30278479/220835627-faad24da-a88c-4d01-91dc-edc8090d388d.png)
结果如下：
![image](https://user-images.githubusercontent.com/30278479/220835738-84822ac9-eb16-453d-82f0-90d5a527b78c.png)

**Comment by SlimeNull** [comment]
我去看看是否有这个问题存在

**Comment by SlimeNull** [comment]
雀食有这个逻辑问题, 这就去改

**Comment by SlimeNull** [comment]
新的 nuget 包已提交, 大概在几分钟之后就可以使用了, 感谢提交 issue
![](https://github.com/SlimeNull/SlimeNull/blob/main/img/qwq.gif)

**Comment by wearshoes** [comment]
我焯 大佬太感谢了 我一直以为是我调用有问题 然后怀疑了一晚上是不是自己看不懂代码 我焯！！！
