### ISSUE TITLE
自动构建

### ISSUE THREAD

**Issue by JWJUN233233** [OrgEleCho/EleCho.GoCqHttpSdk#16]
action自动构建不完整

**Comment by SlimeNull** [comment]
不会写啊 QAQ

**Comment by JWJUN233233** [comment]
来抄我写的 https://github.com/Blessing-Studio/WonderLab
.github文件夹里

**Comment by JWJUN233233** [comment]
要不我给你写
下周或下下周写好了给你提pr

**Comment by JWJUN233233** [comment]
看你搞得挺困难的

**Comment by SlimeNull** [comment]
我是很奇怪，为啥我在Windows上dotnet build能成功，但是Ubuntu上就不行。

而且更奇怪的是，第一次执行dotnet build会失败，但是啥也不动，直接再执行一次，就能成功构建了…

只能说是玄学问题了。具体报错还目前的action是一样的。我是使用的wsl进行测试。

**Comment by JWJUN233233** [comment]
> 我是很奇怪，为啥我在Windows上dotnet build能成功，但是Ubuntu上就不行。
> 
> 而且更奇怪的是，第一次执行dotnet build会失败，但是啥也不动，直接再执行一次，就能成功构建了…
> 
> 只能说是玄学问题了。具体报错还目前的action是一样的。我是使用的wsl进行测试。

我大概知道了 是你用了netstd2.0
ubuntu的ci镜像自带dotnet7

**Comment by SlimeNull** [comment]
那如何才能让他一次性构建成功呢

**Comment by JWJUN233233** [comment]
> 那如何才能让他一次性构建成功呢

装上netstd2.0就好了

**Comment by JWJUN233233** [comment]
等会写好我提pr

**Comment by JWJUN233233** [comment]
似乎无药可救了
netstd没法安装

**Comment by JWJUN233233** [comment]
原来是你写的有问题
你写的代码不支持netstandard2.0

**Comment by SlimeNull** [comment]
好了, 我让他自动构建 dll 了, nuget 包就算了 (
