### ISSUE TITLE
正则表达匹配是否有问题

### ISSUE THREAD

**Issue by wearshoes** [OrgEleCho/EleCho.GoCqHttpSdk#17]
![image](https://user-images.githubusercontent.com/30278479/223473505-fe68cff5-e5f1-4fd9-914e-d815676a265e.png)
这样写的话 程序整个就卡主了

**Comment by SlimeNull** [comment]
我去看看

**Comment by SlimeNull** [comment]
我注意到你在第二个方法上添加了 string content 参数, 但是在正则中却不存在这个分组, 按理说, 这种情况, 你会得到一个 Exception, 更不会正常执行的

**Comment by SlimeNull** [comment]
这个 Exception 不会被捕捉, 因为它会在你的会话主循环线程中被抛出, 这导致主循环线程停止.

**Comment by SlimeNull** [comment]
( 另外, 根据你的 issue, 我现在将插件方法的检查放到了构造函数里, 这样你就能直接看到异常了, 你可以更新包 )

**Comment by wearshoes** [comment]
大佬牛逼 太感谢了
