### ISSUE TITLE
崩溃bug2

### ISSUE THREAD

**Issue by JWJUN233233** [OrgEleCho/EleCho.GoCqHttpSdk#22]
![image](https://user-images.githubusercontent.com/66861021/224520821-8d333995-b20c-4c4c-8372-91a75a06eae2.png)
![image](https://user-images.githubusercontent.com/66861021/224520825-7cd6e563-4fe6-4516-aeea-19a1dce1b886.png)
我认为base[0]应改为Add

**Comment by SlimeNull** [comment]
正确的, 已修复并上传 nuget
