### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by JWJUN233233** [OrgEleCho/EleCho.GoCqHttpSdk#25]
1 命令模块添加默认参数支持
2 支持无线长度参数
3 支持处理CqMessage

**Comment by SlimeNull** [comment]
1. 命令模块其实有默认参数支持, 只需要给你的方法参数加上默认值就好, 另外你也可以使用 [NullLib.CommandLine](https://www.nuget.org/packages/NullLib.CommandLine), 它可以视为 [EleCho.CommandLine](https://www.nuget.org/packages/EleCho.CommandLine) (EleCho.GoCqHttpSdk.CommandExecuting 的基础包) 的完整版本. 如果你发现有问题导致你无法正常处理它, 你可以提供更详细的信息.
2. 你可能想说 Variable length parameter, CqMessage 的构造函数中有这个重载, 同时, CqMessage 继承了 IList, 你可以使用列表初始化语句, 它大概是这样: new CqMessage() { 一个消息段, 另一个消息段, 又另一个消息段 }
3. 我不明白你说的支持处理 CqMessage 是什么, 你是指, 提供一个同时处理群消息和私聊消息的方法吗? 因为它们的参数不同, 所以目前没有这样的封装, 不过我会考虑添加的. 如果你说的是 MessageMatching 拓展, 那它其实是已经支持私聊或群聊消息处理了的, 直接在你的方法中使用 CqMessagePostContext 参数即可.

**Comment by JWJUN233233** [comment]
1经过实验 不支持默认参数 默认参数如果在qq的消息中指定了 就无法处理命令
2 指命令  带有[Command]属性类的方法
2 依然指命令 当方法参数类型是CqMessage时 直接将消息传入

**Comment by SlimeNull** [comment]
你尝试安装 EleCho.CommandLine 的最新版本了吗, 默认安装 CommandExecuting 使会安装旧版本

**Comment by SlimeNull** [comment]
第三点是, 如果这么处理的话, 那么会产生耦合, EleCho.GoCqHttpSdk.CommandExecuting 其实只是 EleCho.CommandLine 的封装, 你可以直接使用原始 EleCho.CommandLine 来实现更离谱的功能

**Comment by SlimeNull** [comment]
优化了下
