### ISSUE TITLE
取消禁言bug

### ISSUE THREAD

**Issue by JWJUN233233** [OrgEleCho/EleCho.GoCqHttpSdk#27]
使用CancelBanGroupMember之后无法取消禁言
建议把CancelBanGroupMember方法名改成UnmuteGroupMember

**Comment by SlimeNull** [comment]
我去测试一下, 另外, 如果要改 CancelBanGroupMember 的名称的话, 最好是需要两个都改. 一个是 Mute, 另外一个是 Unmute, 然而 Mute 应该是 "使静音" 的意思, 禁言使用 Mute 似乎不大好.

参考: [禁言-翻译为英语-例句](https://context.reverso.net/%E7%BF%BB%E8%AF%91/%E4%B8%AD%E6%96%87-%E8%8B%B1%E8%AF%AD/%E7%A6%81%E8%A8%80)

**Comment by JWJUN233233** [comment]
取消禁言后会被重新禁言30min

**Comment by SlimeNull** [comment]
修好了, 升级包就可以了
