### ISSUE TITLE
QQ 频道支持

### ISSUE THREAD

**Issue by bsdayo** [OrgEleCho/EleCho.GoCqHttpSdk#34]
go-cqhttp 支持 QQ 频道的消息处理，API 文档在[这里](https://docs.go-cqhttp.org/api/guild.html)

请问频道支持有提上日程吗

**Comment by SlimeNull** [comment]
虽然很想咕咕咕就是了…

**Comment by Saplonily** [comment]
> go-cqhttp 支持 QQ 频道的消息处理，API 文档在[这里](https://docs.go-cqhttp.org/api/guild.html)
> 
> 请问频道支持有提上日程吗

qq 官方提供了api, 相比 go-cqhttp 的完整非常多, 支持大概不是很必要(?
https://bot.q.qq.com/wiki/develop/api/#%E6%8E%A5%E5%8F%A3%E8%AF%B4%E6%98%8E
