### ISSUE TITLE
喔，很棒

### ISSUE THREAD

**Issue by NingLiu1998** [OrgEleCho/EleCho.GoCqHttpSdk#36]
虽然还没开始用，但是看了README 感觉终于有个SDK没有过度封装了，呜呜呜，待我晚点拉包来体验体验

**Comment by SlimeNull** [comment]
其实是有离谱的封装的? 例如很多 Go-CqHttpSdk 的原有命名, 还有数据结构都是封装后的. 包括类型转换都不是直接使用 JSON 反序列化, 因为要方便用户的使用. 总之代码是很屎山啦~ (另外这种讨论性质的内容可以在 Discussions 中进行哦
