### ISSUE TITLE
示例代码中有错误，chain不存在

### ISSUE THREAD

**Issue by NingLiu1998** [OrgEleCho/EleCho.GoCqHttpSdk#37]
![image](https://github.com/OrgEleCho/EleCho.GoCqHttpSdk/assets/109678937/83084ccb-41be-4177-b443-3ebf27eb82ad)

**Comment by SlimeNull** [comment]
抱歉啦, 接口已经变了, 直接使用 CqMessage 的构造函数即可, 其中一个重载是传入 params CqMsg[], 所以可以直接传入多个消息

这是一个示例:
```cs
await actionSession.SendGroupMessageAsync(context.GroupId, new CqMessage(new CqAtMsg(context.UserId), "让我康康你撤回了什么: ", msg.Message, "\n嘿嘿, 撤回失败了吧~"));
```
