### ISSUE TITLE
语音和视频不能正常发送

### ISSUE THREAD

**Issue by NingLiu1998** [OrgEleCho/EleCho.GoCqHttpSdk#38]
# 这是我的代码

![image](https://github.com/OrgEleCho/EleCho.GoCqHttpSdk/assets/109678937/f99713d7-eab8-4523-913e-fab040e3cb32)

# 发送结果

![image](https://github.com/OrgEleCho/EleCho.GoCqHttpSdk/assets/109678937/29fcdf20-13eb-402e-99c3-054a1d64085b)

# cqhttp输出

![image](https://github.com/OrgEleCho/EleCho.GoCqHttpSdk/assets/109678937/65255318-0346-420e-b69f-b0b1c5e49e79)

# 版本说明

版本都是昨天刚下的，全都是拉的最新的

**Comment by NingLiu1998** [comment]
# 补充

![image](https://github.com/OrgEleCho/EleCho.GoCqHttpSdk/assets/109678937/ef1ee842-79ee-4615-bf4e-3568066685c9)

**Comment by SlimeNull** [comment]
这个看样子是 Go-CqHttpSdk 的锅哦, 不是咱的锅. 你可以在 Go-CqHttp 的仓库中提 issue
