### ISSUE TITLE
示例代码中，这个参数怎么传

### ISSUE THREAD

**Issue by NingLiu1998** [OrgEleCho/EleCho.GoCqHttpSdk#40]
# 如图

![image](https://github.com/OrgEleCho/EleCho.GoCqHttpSdk/assets/109678937/571b9595-1ace-420f-9822-d328059103ab)

```
MyMessageMatchPlugin  的入参应该传什么？
```

**Comment by SlimeNull** [comment]
报错信息很清晰了, 需要传入一个 actionSession. 将你的 session 传进去就好了.

> 另外, 建议好好学一下 C# 基础
