### ISSUE TITLE
示例代码中的指令处理入参该填什么？

### ISSUE THREAD

**Issue by NingLiu1998** [OrgEleCho/EleCho.GoCqHttpSdk#41]
` public MyMessageMatchPlugin(ICqActionSession actionSession) `

直接传显然也是不对头

![image](https://github.com/OrgEleCho/EleCho.GoCqHttpSdk/assets/109678937/b98d3e4a-08a0-4791-8c8b-19c8ff535b06)

点进这个类里面也没看到继承什么共同类，所以我该传递什么参数进去？

**Comment by NingLiu1998** [comment]
实际上需要这样

![3M4{SA9 X(@824X(SP3W5H1](https://github.com/OrgEleCho/EleCho.GoCqHttpSdk/assets/109678937/f36ce8a1-7308-4776-8843-bc709843fabb)

**Comment by SlimeNull** [comment]
指令处理和 MessageMatchPlugin 是两个东西噢, MessageMatch 是消息匹配, 指令处理是内置指令解析的玩意儿.

使用 `session.UseCommandExecutePlugin` 方法就可以使用 "指令处理" 插件了
