### ISSUE TITLE
发送图片文件，相对路径和绝对路径都尝试不行

### ISSUE THREAD

**Issue by NingLiu1998** [OrgEleCho/EleCho.GoCqHttpSdk#42]
# 提示错误

![image](https://github.com/OrgEleCho/EleCho.GoCqHttpSdk/assets/109678937/6db44070-080e-4ce0-af4b-131df4d619c1)

![image](https://github.com/OrgEleCho/EleCho.GoCqHttpSdk/assets/109678937/2021b178-d07a-4c50-a041-089664bdebe0)

# 我的代码

![image](https://github.com/OrgEleCho/EleCho.GoCqHttpSdk/assets/109678937/f7be8e2d-f6cf-4282-9fba-542543ab67d8)

**Comment by JWJUN233233** [comment]
建议使用base64

**Comment by SlimeNull** [comment]
你可能需要使用 `file:///` 协议. 这是 Go-CqHttp 设计问题

go-cqhttp 支持 base64, 也支持文件, 但是它是通过 URI 的格式传的. 这就发生了一个问题. URI 标准是不支持太长的地址的. 没有办法直接将 base64 存入到 Uri 对象中.

而使用字符串的话, 用户又可能会感到迷惑, 例如用户会不知道我应该传什么.

不过, 如果看文档的话, 所有问题就迎刃而解了. 关于传输图片, 音频, 文件这类, 还是以 go-cqhttp 文档为准
