### ISSUE TITLE
...我觉着文档既然容易误导，不如直接说一句去看demo

### ISSUE THREAD

**Issue by NingLiu1998** [OrgEleCho/EleCho.GoCqHttpSdk#43]
### 文档所示
![{H22Z8CSJJT}0SM_ET7QAGW](https://github.com/OrgEleCho/EleCho.GoCqHttpSdk/assets/109678937/a4cfa2a5-2944-4142-9f9b-a0fed49504e0)

### 我就按照这种尝试了半天

![47}CKPT_%I@~6PKE$ R4K}Y](https://github.com/OrgEleCho/EleCho.GoCqHttpSdk/assets/109678937/f761f8f7-0404-4695-82aa-9a60b1519e32)

### 最后翻到demo里面才知道要这样

![3M4{SA9 X(@824X(SP3W5H1](https://github.com/OrgEleCho/EleCho.GoCqHttpSdk/assets/109678937/d305f4c5-fb48-4192-9a06-54f26ae282c7)

**Comment by NingLiu1998** [comment]
毕竟是开源项目，也没有理由强制要求文档啥的非常完善，我也是看到README里面提到鼓励多提iss，我才按照文档走，把流程遇到卡主的的问题提一下，如果实在没这个必要，那就算了

**Comment by Iviaca** [comment]
蛤蛤蛤我居然没有这个问题（一看原来是自己tab按太快了自动填充进去惹

不过我一开始是没看到md文档，直接看得demo

希望这个项目能继续完善下去叭

**Comment by Iviaca** [comment]
蛤蛤蛤我居然没有这个问题（一看原来是自己tab按太快了自动填充进去惹

不过我一开始是没看到md文档，直接看得demo

希望这个项目能继续完善下去叭

**Comment by SlimeNull** [comment]
文档不完善确实很抱歉了, 其实这个不看文档, 光是靠代码提示也能非常简单的写很多东西了.

我会把你的提议加到 readme 中的.
