### ISSUE TITLE
是否可以给Session的连接方法提供同步方法

### ISSUE THREAD

**Issue by culat** [OrgEleCho/EleCho.GoCqHttpSdk#6]
1. 在Session启动连接后，必须手动阻塞线程，是否可以增加同步方法
2. 是否应该把构造方法中的启动线程操作([CqWsSession.cs#L76](https://github.com/OrgEleCho/EleCho.GoCqHttpSdk/blob/master/GoCqHttp.Sdk/CqWsSession.cs#L76))移到连接方法中

**Comment by SlimeNull** [comment]
好了捏
