### ISSUE TITLE
是否应该将CqSession类更改为接口并抽象出方法

### ISSUE THREAD

**Issue by culat** [OrgEleCho/EleCho.GoCqHttpSdk#7]
为什么[CqSession](https://github.com/OrgEleCho/EleCho.GoCqHttpSdk/blob/master/GoCqHttp.Sdk/CqSession.cs#L3)是一个空类啊, 哼, 哼, 哼, 啊啊啊啊啊啊啊啊啊

**Comment by SlimeNull** [comment]
改个p, 哼哼哼, 啊啊啊啊啊啊, 这种关系到优雅与否的问题, 请在 Discussion 里面写啊哼哼哼啊啊啊啊啊啊啊啊啊啊

(臭死了)
